// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/topic": {
    params: {};
  };
  "/quiz": {
    params: {};
  };
  "/results": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/register" | "/login" | "/topic" | "/quiz" | "/results";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/topic.tsx": {
    id: "routes/topic";
    page: "/topic";
  };
  "routes/quiz.tsx": {
    id: "routes/quiz";
    page: "/quiz";
  };
  "routes/results.tsx": {
    id: "routes/results";
    page: "/results";
  };
};